/* tslint:disable */
/* eslint-disable */
/**
 * SyskenGacha-backend
 * SyskenGachaのバックエンド。 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AdminUploadPostRequest
 */
export interface AdminUploadPostRequest {
    /**
     * 
     * @type {Blob}
     * @memberof AdminUploadPostRequest
     */
    file?: Blob;
    /**
     * 
     * @type {string}
     * @memberof AdminUploadPostRequest
     */
    name?: string;
}
