/* tslint:disable */
/* eslint-disable */
/**
 * SyskenGacha-backend
 * SyskenGachaのバックエンド。 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GachaItem } from './gacha-item';
/**
 * 
 * @export
 * @interface GachaList
 */
export interface GachaList {
    /**
     * 
     * @type {Array<GachaItem>}
     * @memberof GachaList
     */
    gachaList?: Array<GachaItem>;
}
