/* tslint:disable */
/* eslint-disable */
/**
 * SyskenGacha-backend
 * SyskenGachaのバックエンド。 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GachaItem
 */
export interface GachaItem {
    /**
     * 
     * @type {number}
     * @memberof GachaItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GachaItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GachaItem
     */
    pictId?: string;
    /**
     * 
     * @type {number}
     * @memberof GachaItem
     */
    rare?: number;
}
