/*
 * SyskenGacha-backend
 *
 * SyskenGachaのバックエンド。
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GachaItem struct {
	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	PictId string `json:"pictId,omitempty"`

	Rare int64 `json:"rare,omitempty"`

	Source string `json:"source,omitempty"`
}
