/*
 * SyskenGacha-backend
 *
 * SyskenGachaのバックエンド。 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GachaList struct {

	GachaList []GachaItem `json:"gachaList,omitempty"`
}
